%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 611.4509887695312
Camera.fy: 611.4857177734375
Camera.cx: 433.2039794921875
Camera.cy: 249.4730224609375

# Camera distortion parameters (OpenCV)
Camera.k1: 0.05686357617378235
Camera.k2: 0.3948138356208801 
Camera.p1: -0.0014198372373357415
Camera.p2: -0.0017631723312661052
Camera.k3: -1.727744460105896

Camera.width: 848
Camera.height: 480

# IR projector baseline times fx (aprox.)
Camera.bf: 49.833290

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor (what pixel value in the depth image corresponds to 1m?)
DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
